name: Demo jobs with bottle
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Formatting...
        run: black main.py

      - name: Check linting...
        run: flake8 main.py
      
  tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Testing
        run: pytest test.py --doctest-modules
  deployment:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploy...
        run: echo "Deploying..."
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}
    steps:
      - name: Slack
        run: echo "New CI/CD job."

